# Generated by Django 3.2 on 2024-06-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20240627_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '緊急対応ガイド',
                'verbose_name_plural': '緊急対応ガイド',
            },
        ),
    ]
